class MeasureSerializer < ActiveModel::Serializer
  attributes :id,
             :user_id,
             :body_weight,
             :body_fat,
             :calorie,
             :neck,
             :shoulder,
             :chest,
             :left_biceps,
             :right_biceps,
             :left_forearm,
             :right_forearm,
             :upper_abdomen,
             :lower_abdomen,
             :waist,
             :hips,
             :left_thigh,
             :right_thigh,
             :left_calf,
             :right_calf,
             :date,
             :created_at,
             :updated_at
end
